Config:
  Permission-error: true
  Permission-message: "&8&l<&6ServerStuff&8&l> &9You dont have Permissions"
  SyntaxError: ""

Custom-Join:
  Enable: true
  Message: "&8join the server"

Custom-Leave:
  Enable: true
  Message: "&8leave the server"

