name: ServerStuff
version: 1.0.0.0
main: net.minecraft.serverstuff.ServerStuff
api-version: 1.13
authors: [TonimatasMC, danizml]
description: Add a lot of things.

commands:
  plugin:
    description: Enable or disable plugins.
    permission: serverstuff.plugin
  serverstuff:
    description: MainCommand
    permission: serverstuff.severstuff

permissions:
  serverstuff.serverstuff.*:
    description: Main command permission.
    default: false
    children:
      - serverstuff.reload
      - serverstuff.help

  serverstuff.plugin.*:
    description: Plugin command permission.
    default: false
    children:
      - serverstuff.plugin.enable
      - serverstuff.plugin.disable

  serverstuff.plugin.enable:
    description: Enable plugin command permission.
    default: false

  serverstuff.plugin.disable:
    description: Disable plugin command permission.
    default: false

  serverstuff.help:
    description: help command permission.
    default: false

  serverstuff.reload:
    description: Reload the plugin permission.
    default: false

