name: ServerStuff
version: 1.0.0.0
main: main.serverstuff.ServerStuff
api-version: 1.13
authors: [TonimatasDEV, danizml]
description: Add a lot of things.

commands:
  fly:
    description: Fly command
    permission: serverstuff.fly
  plugin:
    description: Enable or disable plugins.
    permission: serverstuff.plugin
  serverstuff:
    description: MainCommand
    permission: serverstuff.serverstuff
  speed:
    description: Speed command.
    permission: serverstuff.speed
  tpa:
    description: Tpa command.
    permission: serverstuff.tpa
  tpoffline:
    description: Tp offline command.
    permission: serverstuff.tpoffline
  workbench:
    description: workbench.
    permission: serverstuff.workbench
    aliases:
      - wb
  god:
    description: God command.
    permission: serverstuff.god

permissions:
  serverstuff.*:
    description: Main plugin permission.
    children:
      - serverstuff.serverstuff.*
      - serverstuff.plugin.*
      - serverstuff.speed.*
      - serverstuff.tpoffline
      - serverstuff.fly.*
      - serverstuff.workbench.*
      - serverstuff.god.*

  serverstuff.speed.*:
    description: Speed command permission.
    children:
      - serverstuff.speed.fly
      - serverstuff.speed.walk
      - serverstuff.speed.both
      - serverstuff.speed.other.*

  serverstuff.tpoffline:
    description: Tp offline command permission.

  serverstuff.speed.fly:
    description: Speed command permission.

  serverstuff.speed.walk:
    description: Speed command permission.

  serverstuff.speed.both:
    description: Speed command permission.

  serverstuff.speed.other.*:
    description: Speed other command permission.
    children:
      - serverstuff.speed.other.fly
      - serverstuff.speed.other.both
      - serverstuff.speed.other.walk

  serverstuff.speed.other.fly:
    description: Speed command permission.

  serverstuff.speed.other.walk:
    description: Speed other command permission.

  serverstuff.speed.other.both:
    description: Speed other command permission.

  serverstuff.serverstuff.*:
    description: Main command permission.
    children:
      - serverstuff.reload
      - serverstuff.help

  serverstuff.plugin.*:
    description: Plugin command permission.
    children:
      - serverstuff.plugin.enable
      - serverstuff.plugin.disable

  serverstuff.plugin.enable:
    description: Enable plugin command permission.

  serverstuff.plugin.disable:
    description: Disable plugin command permission.

  serverstuff.help:
    description: help command permission.

  serverstuff.reload:
    description: Reload the plugin permission.

  serverstuff.fly.other:
    description: Fly other permission.

  serverstuff.fly:
    description: Fly permission.

  serverstuff.fly.*:
    description: All fly permissions.
    children:
      - serverstuff.fly
      - serverstuff.fly.other

  serverstuff.workbench.*:
    description: Workbench command other permission.
    children:
      - serverstuff.workbench.other
      - serverstuff.workbench

  serverstuff.workbench.other:
    description: Workbench command other permission.

  serverstuff.workbench:
    description: Workbench command permission.

  serverstuff.god.*:
    description: Workbench command other permission.
    children:
      - serverstuff.god.other
      - serverstuff.god

  serverstuff.god.other:
    description: God other command permission.

  serverstuff.god:
    description: God command permission.
