name: ServerStuff
version: 1.0.0.0
main: main.serverstuff.ServerStuff
api-version: 1.13
authors: [TonimatasMC, danizml]
description: Add a lot of things.

commands:
  plugin:
    description: Enable or disable plugins.
    permission: serverstuff.plugin
  serverstuff:
    description: MainCommand
    permission: serverstuff.serverstuff

permissions:
  serverstuff.*:
    description: Main plugin permission.
    children:
      - serverstuff.serverstuff.*
      - serverstuff.plugin.*

  serverstuff.serverstuff.*:
    description: Main command permission.
    children:
      - serverstuff.reload
      - serverstuff.help

  serverstuff.plugin.*:
    description: Plugin command permission.
    children:
      - serverstuff.plugin.enable
      - serverstuff.plugin.disable

  serverstuff.plugin.enable:
    description: Enable plugin command permission.

  serverstuff.plugin.disable:
    description: Disable plugin command permission.

  serverstuff.help:
    description: help command permission.

  serverstuff.reload:
    description: Reload the plugin permission.


